### ISSUE TITLE
Fix NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [tDOM/tdom#12]
The TEA autoconf macros incorrectly assume that NetBSD is some weird old operating system that can't handle dots in library names.

**Comment by 0-wiz-0** [comment]
```
--- configure.orig      2007-08-05 20:47:49.000000000 +0200
+++ configure   2011-12-29 03:13:10.000000000 +0100
@@ -8283,7 +8283,7 @@
            CC_SEARCH_FLAGS=""
            LD_SEARCH_FLAGS=""
            ;;
-       NetBSD-*|FreeBSD-[1-2].*)
+       FreeBSD-[1-2].*)
            # NetBSD/SPARC needs -fPIC, -fpic will not do.
            SHLIB_CFLAGS="-fPIC"
            SHLIB_LD="ld -Bshareable -x"
@@ -8388,7 +8388,7 @@
            UNSHARED_LIB_SUFFIX='${TCL_TRIM_DOTS}.a'
            TCL_LIB_VERSIONS_OK=nodots
            ;;
-       FreeBSD-*)
+       NetBSD-*|FreeBSD-*)
            # FreeBSD 3.* and greater have ELF.
            SHLIB_CFLAGS="-fPIC"
            SHLIB_LD="ld -Bshareable -x"
```

**Comment by pointsman** [comment]
Do you know, if this is fixed in current TEA? (The TEA version used by tdom atm surely isn't up to date.)

**Comment by 0-wiz-0** [comment]
Sorry, no clue. Where's TEA's upstream location so we can check?

**Comment by pointsman** [comment]
TEA's current location is the fossil repository at http://core.tcl.tk/sampleextension/
Click at the newest entry in the timeline - that will bring you to a details page. At that page you will find 'tar' and 'zip' links to the whole package code.

**Comment by 0-wiz-0** [comment]
NetBSD part is fixed in upstream.
For reference: The original upstream is tcl itself, unix/tcl.m4, which is used when generating configure from configure.in.

**Comment by pointsman** [comment]
TEA build system updated from upstream. Please check.

**Comment by 0-wiz-0** [comment]
I think it's fine now.
It builds and 'make test' is happy except for two tests it skips.

Just for the record, here are the compiler warnings I see with gcc-4.5.4:
./generic/domxpath.c: In function ‘StepPattern’:
./generic/domxpath.c:1914:54: warning: ‘savedmax’ may be used uninitialized in this function
./generic/domxpath.c:1914:49: warning: ‘max’ may be used uninitialized in this function
./generic/domxpath.c: In function ‘xpathEval’:
./generic/domxpath.c:5240:20: warning: ‘h’ may be used uninitialized in this function

./generic/domxslt.c:468:13: warning: ‘printXML’ defined but not used
./generic/domxslt.c: In function ‘evalAttrTemplates’:
./generic/domxslt.c:3320:55: warning: ‘literalChar’ may be used uninitialized in this function

and here with clang-3.4 (trunk 185778):

./expat/xmlparse.c:1568:18: warning: implicit conversion from enumeration type 'enum XML_Status' to different enumeration type 'enum XML_Error' [-Wenum-conversion]
        result = XML_STATUS_SUSPENDED;
               ~ ^~~~~~~~~~~~~~~~~~~~
./expat/expat.h:51:30: note: expanded from macro 'XML_STATUS_SUSPENDED'
#define XML_STATUS_SUSPENDED XML_STATUS_SUSPENDED
                             ^~~~~~~~~~~~~~~~~~~~
./expat/xmlparse.c:1578:18: warning: implicit conversion from enumeration type 'enum XML_Status' to different enumeration type 'enum XML_Error' [-Wenum-conversion]
        result = XML_STATUS_OK;
               ~ ^~~~~~~~~~~~~
./expat/expat.h:49:23: note: expanded from macro 'XML_STATUS_OK'
#define XML_STATUS_OK XML_STATUS_OK
                      ^~~~~~~~~~~~~
./expat/xmlparse.c:1608:12: warning: implicit conversion from enumeration type 'enum XML_Error' to different enumeration type 'enum XML_Status' [-Wenum-conversion]
    return result;
    ~~~~~~ ^~~~~~
3 warnings generated.
./generic/domxslt.c:1889:29: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
        if ((node->nodeType == ATTRIBUTE_NODE)) {
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
./generic/domxslt.c:1889:29: note: remove extraneous parentheses around the comparison to silence this warning
        if ((node->nodeType == ATTRIBUTE_NODE)) {
            ~               ^                ~
./generic/domxslt.c:1889:29: note: use '=' to turn this equality comparison into an assignment
        if ((node->nodeType == ATTRIBUTE_NODE)) {
                            ^~
                            =
./generic/domxslt.c:468:13: warning: function 'printXML' is not needed and will not be emitted [-Wunneeded-internal-declaration]
static void printXML (domNode *node, int level, int maxlevel) {
            ^
2 warnings generated.
./generic/tclexpat.c:963:15: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
              close (fd);
              ^
./generic/tclexpat.c:969:19: warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]
          nread = read(fd, fbuf, READ_SIZE);
                  ^
2 warnings generated.

This doesn't break the build, I just thought I'd mention them so you can fix them.
