### ISSUE TITLE
getLine does not seem to work

### ISSUE THREAD

**Issue by htv2012** [tDOM/tdom#17]
I tried to use `getLine` to get the line number for a particular node and it does not seem to work. Instead, getLine returned an error. See the code sample below:

```
package require tdom
package require Tclx

# Contents of message.xml:
# <Message>
# <Subject>Test Message 1</Subject>
# </Message>

# Why does getLine not work?
set f [open message.xml]
set doc [dom parse -channel $f]
close $f
set node [$doc getElementsByTagName Subject]
puts [$node getLine]; # Error: no line/column information available!
```

**Comment by pointsman** [comment]
Line/column information is only stored on request. Add

dom setStoreLineColumn 1

within your example code before you parse the document and everything should work as expected.

See the documentation for the setStoreLineColumn method of the dom command (http://tdom.github.io/dom.html)

**Comment by htv2012** [comment]
Thank you for the quick and accurate response.
