### ISSUE TITLE
tnc tests file version mismatch

### ISSUE THREAD

**Issue by rich123** [tDOM/tdom#19]
The tnc tests Tcl source file that ships with tDOM 0.8.3 (extensions/tnc/tests/loadtnc.tcl) is hardwired to attempt to load only tDOM 0.7.5.

The result is that the tests fail with 0.8.3 with a message that tdom 0.7.5 can not be found.

**Comment by pointsman** [comment]
Are you sure, you're using trunk head?

**Comment by rich123** [comment]
In the tar.gz bundle linked from here: http://tdom.github.io/ as "The latest tDOM source release is tDOM-0.8.3 (967k gzip tar archive)" it is out of sync.

Didn't try trunk/head.

**Comment by pointsman** [comment]
This was already fixed while updating the TEA build system of tDOM and the extensions, within the last few months.
