### ISSUE TITLE
xsl:sort crashes on 64 bit systems

### ISSUE THREAD

**Issue by danckaert** [tDOM/tdom#2]
There is a bug in domxslt.c which causes xsl:sort to crash on 64 bit systems. To fix it, change line 2682 of domxslt.c from:

```
memcpy(posa, posb,  size*sizeof(int*));
```

to:

```
memcpy(posa, posb,  size*sizeof(int));
```

**Comment by pramaku** [comment]
Hi,
Can you let me know on which tDom this issue has been fixed.
Thanks in advance.

**Comment by jcaruso** [comment]
A client of mine ran into this issue as well and it ended up costing us weeks of bug hunting, since the bug causes memory corruption which is difficult to trace to the fastMergeSort function.

**Comment by pointsman** [comment]
Danckaert is right. The bug is fixed in trunk.
