### ISSUE TITLE
tdom 0.8.3 fails to compile on SPARC Solaris 9

### ISSUE THREAD

**Issue by lvirden** [tDOM/tdom#3]
Platform: SPARC Solaris 9, Sun C compiler, Tcl CVS head today (8.6bsomething...)

When trying to compile tdom 0.8.3, I see several warnings, followed by an error that stops the build process.  

The warnings are:
/opt/SUNWspro/bin/cc -DPACKAGE_NAME=\"tdom\" -DPACKAGE_TARNAME=\"tdom\" -DPACKAG
E_VERSION=\"0.8.3\" -DPACKAGE_STRING=\"tdom\ 0.8.3\" -DPACKAGE_BUGREPORT=\"\" -D
STDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE
_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_UNIS
TD_H=1 -DWORDS_BIGENDIAN=1 -DHAVE_LIMITS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_MEMMOVE
=1 -DHAVE_BCOPY=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_POSIX_PTHREAD_SEMANTICS
=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -D_REENTRANT=1 -D_POSIX_PTHREAD_SEMANTICS=1
-DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_DIRENT64=1 -DHAVE_STRUCT_STAT64=1 -
DHAVE_OPEN64=1 -DHAVE_LSEEK64=1 -DHAVE_TYPE_OFF64_T=1 -DUSE_TCL_STUBS=1 -DXML_DT
D=1 -DXML_NS=1 -DTDOM_NO_UNKNOWN_CMD=1 -DUSE_NORMAL_ALLOCATOR=1   -I../generic -
I../expat -I"/vol/tclsrcsol/tcl86/tcl/generic"    -g  -KPIC  -c `echo ../expat/x
mlparse.c` -o xmlparse.o
"../expat/xmlparse.c", line 1493: warning: enum type mismatch: op "="
"../expat/xmlparse.c", line 1497: warning: enum type mismatch: op "="
"../expat/xmlparse.c", line 1500: warning: enum type mismatch: op "="
"../expat/xmlparse.c", line 1535: warning: enum type mismatch: op "="

and later
"../generic/domhtml.c", line 925: warning: end-of-loop code not reached

and finally

/opt/SUNWspro/bin/cc -DPACKAGE_NAME=\"tdom\" -DPACKAGE_TARNAME=\"tdom\" -DPACKAG
E_VERSION=\"0.8.3\" -DPACKAGE_STRING=\"tdom\ 0.8.3\" -DPACKAGE_BUGREPORT=\"\" -D
STDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE
_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_UNIS
TD_H=1 -DWORDS_BIGENDIAN=1 -DHAVE_LIMITS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_MEMMOVE
=1 -DHAVE_BCOPY=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_POSIX_PTHREAD_SEMANTICS
=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -D_REENTRANT=1 -D_POSIX_PTHREAD_SEMANTICS=1
-DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_DIRENT64=1 -DHAVE_STRUCT_STAT64=1 -
DHAVE_OPEN64=1 -DHAVE_LSEEK64=1 -DHAVE_TYPE_OFF64_T=1 -DUSE_TCL_STUBS=1 -DXML_DT
D=1 -DXML_NS=1 -DTDOM_NO_UNKNOWN_CMD=1 -DUSE_NORMAL_ALLOCATOR=1   -I../generic -
I../expat -I"/vol/tclsrcsol/tcl86/tcl/generic"    -g  -KPIC  -c `echo ../generic
/tcldom.c` -o tcldom.o
"../generic/tcldom.c", line 5937: undefined struct/union member: errorLine
cc: acomp failed for ../generic/tcldom.c
gmake: **\* [tcldom.o] Error 2

**Comment by lvirden** [comment]
In Tcl 8.6, generic/tcl.h contains this code:
typedef struct Tcl_Interp {
    /\* TIP #330: Strongly discourage extensions from using the string
     \* result. _/
#ifdef USE_INTERP_RESULT
    char *result;               /_ If the last command returned a string
                                 \* result, this points to it. _/
    void (_freeProc) (char _blockPtr);
                                /_ Zero means the string result is statically
                                 \* allocated. TCL_DYNAMIC means it was
                                 \* allocated with ckalloc and should be freed
                                 \* with ckfree. Other values give the address
                                 \* of function to invoke to free the result.
                                 \* Tcl_Eval must free it before executing next
                                 \* command. _/
#else
    char *unused3;
    void (_unused4) (char _);
#endif
#ifdef USE_INTERP_ERRORLINE
    int errorLine;              /_ When TCL_ERROR is returned, this gives the
                                 \* line number within the command where the
                                 \* error occurred (1 if first line). */
#else
    int unused5;
#endif
} Tcl_Interp;

It appears to me that tdom currently expects USE_INTERP_ERRORLINE to be defined - 5937 is a reference to interp->errorLine ...

**Comment by joosera** [comment]
This might be relevant, I had problems compiling tDOM with TCL version 8.6 and I came up with this fix: https://github.com/joosera/tdom/commit/156102b039634b5659df97b4d1d29c8df22c97de
