### ISSUE TITLE
tDOM max 3 byte utf-8 sequence abort

### ISSUE THREAD

**Issue by rich123** [tDOM/tdom#4]
tDOM (Linux 0.8.3) contains a check when outputing an XML document on the utf-8 byte length of individual characters, and aborts the entire Tcl process if an attempt is made to output an XML document containing characters that would be longer than a 3 byte utf-8 sequence.

Given that it appears that modern Tcl's natively handle longer than 3 byte utf-8 characters:

(tcl 8.5.8):
set fd [ open utf8test {WRONLY CREAT TRUNC} ]
fconfigure $fd -encoding utf-8 
puts -nonewline $fd \u1d50d
close $fd 

Then note that "utf8test" is four bytes in length.

It would be nice if tDOM were updated to remove this 3-byte utf-8 limitation.

If removal is not possible, then it would be nice that if instead of aborting, tDOM simply output a character escape (&#12345; or &#xa234f;) for the overlong character and continued as if nothing were wrong.

Barring that, it would be nice if the abort were a simple error that could be caught with a catch {} so that a script could detect and handle the occurrence.

**Comment by pointsman** [comment]
No, even modern Tcl (8.5.8 or 8.6b2) doesn't handle longer than 3 bytes utf 8 chars. (Well, you can modify the source code to get something like that, but how well this works need testing. If you build the sources as shipped, you get only up to 3 bytes utf-8 chars). In your example the output file has the 3 byte utf-8 char (\u1d50) and the 1 byte char 'd', that sums up to the 4 bytes in length you see.

If you trigger that panic, then you almost always have a massive encoding problem. Not just something wrong (e.g, a wrong encoding in a fconfigure), but deeply broken. In other words: you have a very important problem. It wasn't just (or only) lazyness, to not unwind that up to a tcl error, it was a deliberate decision to put the noise of the programmer as hard as possible into that problem. In retrospection, that wasn't the best possible decision, given that there are too many programmers out there, which insit in being able to [catch] away problems they should look into.

**Comment by rich123** [comment]
> If you trigger that panic, then you almost always have a massive encoding problem.

I had the panic trigger by parsing an XML file that contained hex escapes for that exact character &#x1d50d; (http://www.marathon-studios.com/unicode/U1D50D/Mathematical_Fraktur_Capital_J).  TDOM swallowed the file with no complaints, but upon attempting to save it back out, TDom panicked.  What surprised me was that even when I switched to -escapeNonASCII, tDom still panicked, even though the docs appear to state that -escapeNonASCII will escape character value that is larger than 0x7f.  I ended up using a work around where I escaped the hex encoded character escapes so that tDom would not parse them, and then unescaped them upon output.  So what I had does not appear to have been an encoding problem (the input XML was properly escaped) but rather a case where tDom would consume something that it then refused to recreate.

**Comment by pointsman** [comment]
rich123 wrote:

> > If you trigger that panic, then you almost always have a massive
> > encoding problem.
> 
> I had the panic trigger by parsing an XML file that contained hex
> escapes for that exact character &#x1d50d;
> (http://www.marathon-studios.com/unicode/U1D50D/Mathematical_Fraktur_Capital_J).
> TDOM swallowed the file with no complaints, but upon attempting to
> save it back out, TDom panicked.  What surprised me was that even
> when I switched to -escapeNonASCII, tDom still panicked, even though
> the docs appear to state that -escapeNonASCII will escape character
> value that is larger than 0x7f.  I ended up using a work around
> where I escaped the hex encoded character escapes so that tDom would
> not parse them, and then unescaped them upon output.  So what I had
> does not appear to have been an encoding problem (the input XML was
> properly escaped) but rather a case where tDom would consume
> something that it then refused to recreate.

Yes, that's a possible scenario. And there's an asymetry in digesting
but not give it back.

But you're using the -file option to [dom parse], which by itself uses
the encoding capabilites of expat. Otherwise, you've no change with
even recent tcl and its 3-byte utf-8 chars, that a [dom parse $xml]
even sees the correct data.

Anyway. You are sure right, I should do something with that code.

rolf

**Comment by pointsman** [comment]
I did almost all I can think of about that with that code. Now, if tDOM parses it, it will give it back, serialized. (Though, for stock tcl and characters beyond BMP always as character entities. For obvious reasons.) There is the new method isBMPCharData, to check, if you are able to savely process that data. There is a new featureinfo subcommand, which tells you, if you need to care. tDOM now 'supports' building with stock tcl and with tcl with TCL_UTF_MAX > 3 (or 4, in case of 8.6). You have to build and use tDOM with such a tcl core with TCL_UTF_MAX > 3 (or 4, in case of 8.6), if you want to process data out of a dom tree with characters beyond BMP,
