### ISSUE TITLE
XSLT to remove comments does not work in tdom

### ISSUE THREAD

**Issue by gwlester** [tDOM/tdom#8]
The following XSLT removes XML comments if run in xsltproc but not in tdom:

```
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="1.0">

  <xsl:template match="comment()"/>

  <!-- Copy all the attributes and other nodes -->
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
```

**Comment by pointsman** [comment]
tDOM is right, xsltproc (at least the version, you're using) is wrong. ;-)

As you reported per mail, you want a stylesheet, that does the identical transformation and just removes all comments while copying the xml input. Your stylesheet don't do that.

For every comment node in the input tree your stylesheet has two matching templates: the match="comment()" as well as the match="@*|node()". See for example the xslt recommendation 1.0, 5.5 Conflict Resolution for Template Rules. Both templates get the same default priority.

If an xslt processor doesn't signal error it must recover by choosing the template rule that occurs last in the stylesheet (see xslt recommendation 1.0, 5.5 Conflict Resolution for Template Rules, last paragraph).

That mean a compliant xslt 1.0 processor as tDOM never choose your template match="comment()", but always the other, which copies everything including comment nodes throu.

To achive, what you try to do just add an explicit priority (higher as the default priority of the other template) to that template:

&lt;xsl:template priority="1" match="comment()"/&gt;

will do it.
